# Docker Compose configuration to support CI operations.
version: "3.7"
services:
  composer:
    image: forumone/composer:2
    volumes:
      - ./:/app:cached

  # Target the final release build stage of the image.
  release:
    build:
      context: ./
      target: release
    environment:
      COMPOSER_AUTH: /;{}

  # Target the final production build stage of the image.
  test:
    build:
      context: ./
      target: test
    volumes:
      - ./.buildkite/artifacts:/var/www/html/artifacts

  # Target the Gesso dependencies stage of the production build.
  gesso:
    build:
      context: ./
      target: gesso
    volumes:
      - ./.buildkite/artifacts:/app/artifacts

volumes:
  fs-data: null
  mysql-data: null
  gesso-patternlab: null
  gesso-css: null
